-- MySQL Script generated by MySQL Workbench
-- Fri Jun  3 00:32:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------customerscustomerscustomers
-- Schema db_109403530
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_109403530` ;

-- -----------------------------------------------------
-- Schema db_109403530
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_109403530` DEFAULT CHARACTER SET utf8 ;
USE `db_109403530` ;

-- -----------------------------------------------------
-- Table `db_109403530`.`member_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403530`.`member_tbl` ;

CREATE TABLE IF NOT EXISTS `db_109403530`.`member_tbl` (
  `member_id` INT NOT NULL,
  `member_name` VARCHAR(100) NOT NULL,
  `phone` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `user_address` VARCHAR(200) NOT NULL,
  `salt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`member_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403530`.`category_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403530`.`category_tbl` ;

CREATE TABLE IF NOT EXISTS `db_109403530`.`category_tbl` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403530`.`status_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403530`.`status_tbl` ;

CREATE TABLE IF NOT EXISTS `db_109403530`.`status_tbl` (
  `status_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403530`.`proposal_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403530`.`proposal_tbl` ;

CREATE TABLE IF NOT EXISTS `db_109403530`.`proposal_tbl` (
  `propoal_id` INT NOT NULL AUTO_INCREMENT,
  `status` INT NOT NULL,
  `category` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `content` VARCHAR(1000) NULL,
  `amount` INT NOT NULL,
  `goal` INT NOT NULL,
  `creat_date` DATE NOT NULL,
  `due_date` DATE NOT NULL,
  PRIMARY KEY (`propoal_id`, `status`, `category`),
  INDEX `proposal_linkto_category_idx` (`category` ASC) VISIBLE,
  INDEX `proposal_linkto_status_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `proposal_linkto_category`
    FOREIGN KEY (`category`)
    REFERENCES `db_109403530`.`category_tbl` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `proposal_linkto_status`
    FOREIGN KEY (`status`)
    REFERENCES `db_109403530`.`status_tbl` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403530`.`ProposalMember_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403530`.`ProposalMember_tbl` ;

CREATE TABLE IF NOT EXISTS `db_109403530`.`ProposalMember_tbl` (
  `member_id` INT NOT NULL,
  `proposal_id` INT NOT NULL,
  PRIMARY KEY (`member_id`, `proposal_id`),
  INDEX `proposalmember_link_to_proposal_idx` (`proposal_id` ASC) VISIBLE,
  CONSTRAINT `proposalmember_link_to_memberid`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_109403530`.`member_tbl` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `proposalmember_link_to_proposal`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_109403530`.`proposal_tbl` (`propoal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403530`.`ProposalOption_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403530`.`ProposalOption_tbl` ;

CREATE TABLE IF NOT EXISTS `db_109403530`.`ProposalOption_tbl` (
  `proposal_id` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `price` INT NOT NULL,
  `description` VARCHAR(1000) NULL,
  PRIMARY KEY (`proposal_id`),
  CONSTRAINT `proposal_id`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_109403530`.`proposal_tbl` (`propoal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403530`.`comment_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403530`.`comment_tbl` ;

CREATE TABLE IF NOT EXISTS `db_109403530`.`comment_tbl` (
  `comment_id` INT NOT NULL,
  `proposal_id` INT NOT NULL,
  `member_id` INT NOT NULL,
  `user_comment` VARCHAR(1000) NULL,
  `proposer_response` VARCHAR(1000) NULL,
  PRIMARY KEY (`comment_id`, `proposal_id`, `member_id`),
  INDEX `comment_link_to_proposalid_idx` (`proposal_id` ASC) VISIBLE,
  INDEX `comment_link_to_memberid_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `comment_link_to_proposalid`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_109403530`.`proposal_tbl` (`propoal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comment_link_to_memberid`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_109403530`.`member_tbl` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403530`.`FAQ_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403530`.`FAQ_tbl` ;

CREATE TABLE IF NOT EXISTS `db_109403530`.`FAQ_tbl` (
  `FAQ` INT NOT NULL,
  `proposal_id` INT NOT NULL,
  `question` VARCHAR(1000) NULL,
  `answer` VARCHAR(1000) NULL,
  `update` DATETIME NULL,
  PRIMARY KEY (`FAQ`, `proposal_id`),
  INDEX `FAQ_link_to_proposalid_idx` (`proposal_id` ASC) VISIBLE,
  CONSTRAINT `FAQ_link_to_proposalid`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_109403530`.`proposal_tbl` (`propoal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403530`.`SponserRecord`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403530`.`SponserRecord` ;

CREATE TABLE IF NOT EXISTS `db_109403530`.`SponserRecord` (
  `sponser_id` INT NOT NULL,
  `member_id` INT NOT NULL,
  `proposal_id` INT NOT NULL,
  `price` INT NULL,
  PRIMARY KEY (`sponser_id`, `proposal_id`, `member_id`),
  INDEX `sponserRecord_linkto_memberid_idx` (`member_id` ASC) VISIBLE,
  INDEX `sponserRecork_linkto_proposalid_idx` (`proposal_id` ASC) VISIBLE,
  CONSTRAINT `sponserRecord_linkto_memberid`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_109403530`.`member_tbl` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sponserRecork_linkto_proposalid`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_109403530`.`proposal_tbl` (`propoal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403530`.`FollowingRecord_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403530`.`FollowingRecord_tbl` ;

CREATE TABLE IF NOT EXISTS `db_109403530`.`FollowingRecord_tbl` (
  `proposal_id` INT NOT NULL,
  `member_id` INT NOT NULL,
  PRIMARY KEY (`proposal_id`, `member_id`),
  INDEX `followRecord_linkto_memberid_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `followRecord_linkto_proposalid`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_109403530`.`proposal_tbl` (`propoal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `followRecord_linkto_memberid`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_109403530`.`member_tbl` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_109403530`.`memberCredential_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_109403530`.`memberCredential_tbl` ;

CREATE TABLE IF NOT EXISTS `db_109403530`.`memberCredential_tbl` (
  `memberCredential_id` INT NOT NULL,
  `hashed_used_id` INT NOT NULL,
  `hashed_pwd_string` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`memberCredential_id`, `hashed_used_id`),
  INDEX `membercredential_linkto_memberid_idx` (`hashed_used_id` ASC) VISIBLE,
  CONSTRAINT `membercredential_linkto_memberid`
    FOREIGN KEY (`hashed_used_id`)
    REFERENCES `db_109403530`.`member_tbl` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
